language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: gmDKkKR3SjCiAHYjA9jUqU6v7RneRQl4+Uma1uLI+ySmZ92frtmXZdfO6zZvsrc2YWYJHmejW47mD3O9TN5lgc6Hu3Au0r8VAiwY0aAj3D+DYFUtAkVdtnfqsizOfIw0zgb/l6FklWeaj5FYR52br688iLJu0yMlKkLMcFQjjcw=
  - secure: itJ/1DlxyzSro/G070jCVUcdDOo3XcASQg23iTMDcvTB+gGHKX8zDyhXpLpCOqSkd9ZLhSnRNo7aeSn5r/Rv5AvuqcDKdMWGpVWf5NFy+oiG88Uw7NAeVRVHCOpcc62Kcc80AfBz4D7J5OltXZZATJgRUqPhCP61AIyl81SZAYI=
